#!/bin/bash
#!/bin/bash
### BEGIN INIT INFO
# Provides:          haproxy
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

HAPROXY_CONF=/etc/haproxy/haproxy.cfg
HAPROXY_PATH=/usr/local/sbin
HAPROXY_DAEMON=$HAPROXY_PATH/haproxy

test -x $HAPROXY_DAEMON || exit 0

set -e

function getHaproxyPID() {
PID=`ps aux | grep 'haproxy -D' | grep -v "grep" | awk '{ print $2 }'`
}

case $1 in
start)
echo "Starting haproxy..."
$HAPROXY_DAEMON -D -f $HAPROXY_CONF
;;
restart)
echo "Hot restart of haproxy"
getHaproxyPID
COMMAND="$HAPROXY_DAEMON -D -f $HAPROXY_CONF -sf $PID"
echo $COMMAND
`$COMMAND`
;;
stop)
echo "Stopping haproxy"
getHaproxyPID
COMMAND="kill -9 $PID"
echo $COMMAND
`$COMMAND`
;;
*)
echo "Usage: haproxyd {start|restart|stop}" >&2
exit 1
;;
esac

exit 0
